# :encoding=UTF-8:
# Pages web generees via jekyll
#
# Pour plus d'informations voir https://jekyllrb.com/

title: pmsixml
email: hkaradimas@ch-sudessonne.fr
description: >- # this means to ignore newlines until "baseurl:"
  Utilisation de métadonnées du PMSI pour automatiser l analyse,
  la génération, et d autres traitements des fichiers à position fixe.
# baseurl: "" # the subpath of your site, e.g. /blog (avant : "/pmsixml")
url: "." # the base hostname & protocol for your site, e.g. http://example.com
destination: ../../build/docs/site

# Build settings
theme: minima
plugins:
  - jekyll-feed

# sass minima bug workaround
# https://github.com/jekyll/minima/issues/709
sass:
  quiet_deps: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
   - .jekyll-cache/

#   - .sass-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
